-- USES MANPOWER TO REIFORCE. THAT SUCKS.
NDefines.NMilitary.CAWA_STARTING_STRENGTH = 0					-- Starting strength of a cawa regiment, 1.0 being full strength
NDefines.NMilitary.CAWA_STARTING_MORALE = 0.1					-- Starting morale of a cawa regiment, 1.0 being full strength
NDefines.NMilitary.CREATE_CAWA_MIL_COST = 5						-- Cost to create Cawa (per unit)
NDefines.NMilitary.CAWA_USES_CONSTRUCTION = 0

--NDefines.NCountry.CORRUPTION_FROM_BANNERS = 2
--NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = -0.05
--NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0
--NDefines.NMilitary.BANNER_MAINTENANCE_COST = 4.0
--NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0
--NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1					-- Starting strength of a banner regiment, 1.0 being full strength
--NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0

--NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 7
--NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 1
--NDefines.NMilitary.JANISSARIES_STARTING_STRENGTH = 0.1
--NDefines.NMilitary.JANISSARIES_STARTING_MORALE = 0.1

NDefines.NMilitary.STRELSKY_STARTING_STRENGTH = 0
NDefines.NMilitary.STRELTSY_STARTING_MORALE = 0.1
NDefines.NMilitary.STRELTSY_USES_CONSTRUCTION = 0

-- NEW STUFF WITH SPECIAL UNITS, KEEPING HERE TO SEE:
--NDefines.NMilitary.CAROLEAN_BASE_COST_MODIFIER = 1.0
--NDefines.NMilitary.CAROLEAN_USES_CONSTRUCTION = 1

--NDefines.NMilitary.HUSSARS_BASE_COST_MODIFIER = 1.0
--NDefines.NMilitary.HUSSARS_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.HUSSARS_STARTING_STRENGTH = 0
NDefines.NMilitary.HUSSARS_STARTING_MORALE = 0.1
NDefines.NMilitary.CREATE_HUSSARS_MIL_COST = 5
NDefines.NMilitary.HUSSARS_USES_CONSTRUCTION = 0

--NDefines.NMilitary.QIZILBASH_USES_CONSTRUCTION = 1
--NDefines.NMilitary.QIZILBASH_BASE_COST_MODIFIER = 0.7
--NDefines.NMilitary.QIZILBASH_MANPOWER_COST_MODIFIER = 1.0
--NDefines.NMilitary.QIZILBASH_LEGITIMACY_COST = 0
--NDefines.NMilitary.QIZILBASH_STARTING_STRENGTH = 1.0
--NDefines.NMilitary.QIZILBASH_STARTING_MORALE = 0.1

--NDefines.NMilitary.MAMLUKS_USES_CONSTRUCTION = 1
--NDefines.NMilitary.MAMLUKS_BASE_COST_MODIFIER = 1.0
--NDefines.NMilitary.MAMLUKS_MANPOWER_COST_MODIFIER = 1.0
--NDefines.NMilitary.MAMLUKS_LEGITIMACY_COST = 0
--NDefines.NMilitary.MAMLUKS_STARTING_STRENGTH = 1.0
--NDefines.NMilitary.MAMLUKS_STARTING_MORALE = 0.1


--NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.04
--NDefines.NMilitary.MERCENARY_REINFORCE_COST_MULTIPLIER = -1.0
--NDefines.NMilitary.MERCENARY_BASE_COST = 10.0
--NDefines.NMilitary.MERCENARY_COMPANY_HIRING_COST_MONTHS = 48
--NDefines.NMilitary.MERCENARY_COMPANY_STARTING_MORALE = 0.5
--NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 4
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 2.5
--NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_RECOVERY = 100
NDefines.NMilitary.MERCENARY_COMPANY_HIRED_MANPOWER_RECOVERY_MOD = 3.0
--NDefines.NMilitary.MERCENARY_COMPANY_LOW_MANPOWER_THRESHOLD = 0.1
--NDefines.NMilitary.MERCENARY_TRADE_RANGE_MODIFIER = 1.0
NDefines.NMilitary.MERCENARY_COMPANY_BUILDING_TIME = 1.4 -- 56 days
--NDefines.NMilitary.MERCENARY_COMPANY_LOCAL_VIRTUAL_DISTANCE = 40
--NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 50.0