-- MJL part:

NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0

NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 35
NDefines.NCountry.PS_NAVAL_BARRAGE = 35
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 50
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3

NDefines.NEconomy.CARAVAN_FACTOR = 3
NDefines.NEconomy.CARAVAN_POWER_MAX = 25
NDefines.NEconomy.CARAVAN_POWER_MIN = 2
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 5475

--NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 10		-- Will see how much affects.
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.2	-- Will see how much affects.

NDefines.NMilitary.MAX_DRAFT_SIZE_TO_YEARLY_INCOME_COST_RATIO = 1.33 -- How much of your yearly income it costs to draft the above ratio's worth of units

NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0

NDefines.NReligion.PIETY_COST = 2 -- Made custom button
NDefines.NReligion.PIETY_ABS_THRESHOLD = 2 -- Made custom button


-- Zlewikk mod part:

NDefines.NGame.END_DATE = "1836.1.2"

NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
--NDefines.NDiplomacy.SPY_NETWORK_TECH_EFFECT = -0.1 -- I forgot what this did.
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 5000

NDefines.NDiplomacy.MAX_FREE_CITIES = 0
NDefines.NDiplomacy.MIN_NUM_ELECTORS_FOR_REMOVE_ELECTORATE = 1
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 1
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.003
--NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.0025
NDefines.NDiplomacy.HRE_HERETIC_PENALTY = 0
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = 0
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_PENALTY_DAYS = 0

NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.06
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 70

NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.3 -- 0.2
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.4 -- -0.3

NDefines.NCountry.HRE_MAX_RANK = 2
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 3

NDefines.NCountry.NAT_FOCUS_YEARS = 15 -- 0
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = 0
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = 0
NDefines.NCountry.DISHONOURED_ALLIANCE_DURATION = 0

NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 15.0
NDefines.NCountry.LIBERTY_DESIRE_DIPLO_TECH = 0

NDefines.NEconomy.EXPELLED_MINORITY_DEV_BONUS_FACTOR = 0.3
NDefines.NEconomy.EXPELLING_MINORITY_SETTLER_CHANCE_FACTOR = 0.005
--NDefines.NEconomy.EDICTS_COST_INCREASE = 0
NDefines.NEconomy.MAX_BUILDING_SLOTS = 16

NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 0
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 2
NDefines.NMilitary.ASSAULT_ATTACKER_LOSS = 1.5
NDefines.NMilitary.WARDEC_COBELLI_FOR_DEFENDER_OF_THE_FAITH = 0

NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 20.0
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 90

NDefines.NMilitary.INFANTRY_BREAKTHROUGH = 0.15
NDefines.NMilitary.CAVALRY_BREAKTHROUGH = 0.25
NDefines.NMilitary.INFANTRY_SPEED = 0.7
NDefines.NMilitary.CAVALRY_SPEED = 0.8
NDefines.NMilitary.ARTILLERY_SPEED = 0.6
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.15
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.15

NDefines.NMilitary.PARTICIPATION_SCORE_BLOCKADE = 0.002
NDefines.NMilitary.PARTICIPATION_SCORE_BATTLE = 0.05
NDefines.NMilitary.PARTICIPATION_SCORE_SIEGE = 0.02
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.2 -- 0.4
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40 -- 25
NDefines.NMilitary.DEFAULT_WARGOAL_WARSCORE_BONUS = 8 -- 5
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 6 -- 3
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 55 -- 40

NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 60.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 0
NDefines.NGovernment.CENTRALIZE_STATE_ADM_COST = 100

-- AI stuff:
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.0 -- Vanilla 1.2
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.5 -- Vanilla 0.8
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 0.5 -- Vanilla 0.85
NDefines.NAI.MIN_CAV_PERCENTAGE = 0 -- Vanilla 5
NDefines.NAI.MAX_CAV_PERCENTAGE = 100 -- Vanilla 50
NDefines.NAI.FOG_OF_WAR_FORGET_CHANCE = 0 -- I wonder how bad it makes AI. Vanilla 1
--NDefines.NAI.FORT_MAINTENANCE_CHEAT = 1 -- Vanilla 0 -- Don't use. Crashes in mp games. MIGHT WORK NOW?
NDefines.NAI.PS_SHORT_TERM_POOL = 0 -- Vanilla 100
NDefines.NAI.AGGRESSIVENESS = 10000 -- Vanilla 200
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 10000 -- Vanilla 300
NDefines.NAI.MISSION_PICK_CHANCE = 100 -- Vanilla 33
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 0 -- Vanilla 6
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 0 -- Vanilla 48
--NDefines.NAI.ARTILLERY_FRACTION = 0.25 -- Vanilla 0.35 # Set to same in vanilla now
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 7 -- Vanilla 11
NDefines.NAI.TRANSPORT_FRACTION = 0.1 -- Vanilla 0.5
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0 -- Vanilla 0.25
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 0.1 -- Vanilla 10
NDefines.NAI.DESIRED_SURPLUS = 0 -- Vanilla 0.1
NDefines.NAI.DESIRED_DEFICIT = 0 -- Vanilla 0.01
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0 -- Vanilla 0.15
NDefines.NAI.MAX_SAVINGS = 0 -- Vanilla 60
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.9 -- Vanilla 0.35
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.3 -- Vanilla 0.15
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.1 -- Vanilla 0.15
NDefines.NAI.ARMY_BUDGET_FRACTION = 2.0 -- Vanilla 0.6
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.1 -- Vanilla 0.3
NDefines.NAI.FORT_BUDGET_FRACTION = 0.2 -- Vanilla 0.3
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 1000 -- Vanilla 100
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 1 -- Vanilla 100
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 100.0 -- Vanilla 4.0
NDefines.NAI.DANGEROUS_OVEREXTENSION_PERCENTAGE = 1.0 -- Vanilla 0.1

NDefines.NAI.DEBASE_THRESHOLD = 0 -- Vanilla 10000
NDefines.NAI.DEVELOPMENT_CAP_BASE = 33 -- Vanilla 10
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 20 -- Vanilla 10
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 0 -- Vanilla 2.0

NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 1 -- Vanilla 3
NDefines.NAI.FIRE_ADVISOR_LOAN_REQUIREMENT = 9 -- Vanilla 5
NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = 0 -- Vanilla 0.5
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = 0 -- Vanilla 1
NDefines.NAI.BUY_INDULGENCE_EXCOM_AI_DESIRE = 0 -- Vanilla 10
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 1000.0 -- Vanilla 10.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 1000.0 -- Vanilla 10.0
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1.0 -- Vanilla 5.0
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 90.0 -- Vanilla 73.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 10.0 -- Vanilla 33.0

NDefines.NAI.COLONY_BUDGET_FRACTION = 1 -- Vanilla 0.4

NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0 -- Vanilla 1.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 2.0 -- Vanilla 0.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 4.0 -- Vanilla 1.5
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.0 -- Vanilla 1.5
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.0 -- Vanilla 0.9
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 2.0 -- Vanilla 1.25
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 2.0 -- Vanilla 1.33
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 2.0 -- Vanilla 1.25
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 2.0 -- Vanilla 0.8
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0 -- Vanilla 0.5